name: Deploy Smart Grocery Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t smartgrocerybot .

      - name: Tag Docker Image
        run: |
          docker tag smartgrocerybot:latest \
          915993063181.dkr.ecr.us-east-1.amazonaws.com/smartgrocerybot:latest

      - name: Push Docker Image to ECR
        run: |
          docker push \
          915993063181.dkr.ecr.us-east-1.amazonaws.com/smartgrocerybot:latest

      - name: Deploy to ECS Fargate
        run: |
          aws ecs update-service \
            --cluster smartgrocery-cluster1 \
            --service smartgrocery-task-service-1lzhrram \
            --force-new-deployment